### ISSUE TITLE
cannot execute the codes. help!!!

### ISSUE THREAD

**Issue by kishore143gn** [samitok/deeppose#4]
when i try GetLSPData it has a lot of errors. somehow when i try to fix it, TrainLSP is bringing error- " the Shape() should have rank atleast 1."
i cant fix it. how can i correct this
can anyone give the correct codes?

**Comment by samitok** [comment]
Are you trying to run "deeppose/Codes/Original/" or "deeppose/Codes/MiniVersion/" ? 
Both was running smoothly when i pushed the last version.

**Comment by kishore143gn** [comment]
original
 import urllib.request as url_request
ImportError: No module named request
this comes in the GetLSP

**Comment by samitok** [comment]
I think urllib.request is a pyhton 3 library. Are you sure that you are using python 3?

**Comment by kishore143gn** [comment]
python 2

**Comment by kishore143gn** [comment]
i have python 3
still the pblm is there

**Comment by samitok** [comment]
Python 3 is run with 'python3' command. Is the error same or different?

**Comment by kishore143gn** [comment]
i cant install tensorflow with python3

**Comment by samitok** [comment]
You should google that
