### ISSUE TITLE
error in dependancy file. cant train

### ISSUE THREAD

**Issue by kishore143gn** [samitok/deeppose#6]
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): /tmp/mnist/mnist_train.tfrecord
	 [[Node: parallel_read/ReaderRead_1 = ReaderRead[_class=["loc:@parallel_read/TFRecordReader_1", "loc:@parallel_read/input_producer"], _device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/TFRecordReader_1, parallel_read/input_producer)]]

**Comment by samitok** [comment]
I have tried the latest code and encountered no such errors.
